# Generated by Django 3.2 on 2021-05-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product1',
            name='brand',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='product1',
            name='hsn',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='product1',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product1',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product1',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
